// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSerial() {
  return window['go']['main']['App']['CloseSerial']();
}

export function GetSerialPorts() {
  return window['go']['main']['App']['GetSerialPorts']();
}

export function OpenSerial(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['OpenSerial'](arg1, arg2, arg3, arg4, arg5);
}

export function SendData(arg1) {
  return window['go']['main']['App']['SendData'](arg1);
}
