// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSerial():Promise<string>;

export function GetSerialPorts():Promise<Array<string>>;

export function OpenSerial(arg1:string,arg2:number,arg3:number,arg4:number,arg5:string):Promise<string>;

export function SendData(arg1:string):Promise<string>;
